### ISSUE TITLE
 [PLEASE READ BEFORE POSTING ISSUES] 📢 The future of Octal

### ISSUE THREAD

**Issue by dangwu** [SUWULLC/Octal#322]
Hey all,

As many of you may be seeing, many of Octal's premium features (logging in, posting replies, favoriting) are currently erroring. I've just been told by Hacker News folks that they're blocking these HTTP web requests (sign in, favorite, reply, etc) from the app due to excessive/unauthorized usage. It was frowned upon for Octal to be making these calls in the first place, as they aren't part of the public Firebase API.

As saddening as it is, I think there's not much I can do at this point. For now, I've removed the Premium in-app purchase from sale. My only course of action may be to update the app to make it a read-only experience. The problem is, I can't currently publish an app update, because Apple keeps rejecting them due to the app not offering a way for users to delete their HN account (which I obviously can't do). So I'm not sure how long it's going to take. 

To be honest, this deprecation may be for the best, as I already didn't have enough time or dedication to properly maintain Octal before this happened. Octal was a pet project that just grew and grew over time, and while it was nice to make a little coffee money, it was definitely not worth the frustrations of working with undocumented HN APIs and dealing with Apple's App Store review process. The app is constantly rejected by Apple for silly reasons (opening HN links in-app, showing HN posts mentioning COVID, not offering account deletion, etc.). The original reason for building the app (fun) has been long gone.

I hope you all understand, and I deeply apologize for this outcome. Thanks for all the support over the years!

**Update**:  I'm in conversation with HN right now about limiting their web API blockage to just the favorites, which is what the app is calling excessively for some unknown reason. Hopefully I can get most app functionality restored and later an app update out that maintains most functionality except probably favorites. Fingers crossed...

Thanks
Daniel

**Comment by luckman212** [comment]
So sad to read this. Octal is far and away my favorite and most useful app on my home screen. I hope somehow the app can continue to exist. I've tried all the others (both paid and free) and they all have some sharp edges. Octal is a thing of beauty. I condemn HN for having a shitty API that nobody ever thought needed to be fixed, and I really hate Apple's ludicrous and draconian approval system that forces people to give up. This is all part of what I feel is the dystopia of modern computing.

**Comment by kevbutler** [comment]
This is so sad to hear.

**Comment by alpinisme** [comment]
This is a real bummer. I’m pretty disappointed in HN for this, since I find it pretty hard to use (small touch targets being among the biggest pain points) and kind of ugly.

**Comment by dangwu** [comment]
I don't think HN needs to be condemned or shamed. They provide great content, for free, with top-notch moderation. As I mentioned before, it's arguably shady for 3rd party apps like Octal to use undocumented/web scraping APIs, even if lots of them do. Additionally, part of what triggered the blockage is that there was apparently a bug where the app could repeatedly make requests to fetch favorites, so I was told they got a *ton* of requests from Octal. It must've started when rebuilding the app with iOS 18 SDK, as the code itself hasn't changed since implementation - but not sure how. Another possibility is that the HN HTML changed and broke the app's fetching functionality - which just further illustrates how this web API usage is all pretty bad.

**Comment by alpinisme** [comment]
Appreciate your straighforwardness and apologies if my comment sounded like it was “shaming”. It’s a bummer all around but I understand why it had to come to this. Thanks for your work. It was just unfortunate to learn we were losing the only way I felt comfortable using the platform.

**Comment by dangwu** [comment]
No worries. I'm actually in conversation with HN right now about just fixing the favorites and account deletion issues and possibly keeping the app mostly in tact. Fingers crossed

**Comment by e40** [comment]
Ah, well.  Sorry to hear it.  When Reddit killed the apps, I stopped using the site.  I will likely still use HN from a browser on my puter, but I will use it a LOT less.  Too bad.

I was happy to support you all these years.  Be well, mate.

**Comment by e40** [comment]
I posted this on HN https://news.ycombinator.com/item?id=41805719
Maybe some visibility will change the situation?

**Comment by dangwu** [comment]
@e40 Nah, actually I prefer if you remove that. I don't want people to think ill of HN, and they're working with me now so I think it's going to be fine.

**Comment by e40** [comment]
> @e40 Nah, actually I prefer if you remove that. I don't want people to think ill of HN, and they're working with me now so I think it's going to be fine.

Deleted.

**Comment by dangwu** [comment]
Thank you! I appreciate your intent though!

**Comment by upgundecha** [comment]
Thanks for the update. I was worried about where all my favorites had gone. Is there a way to recover and export the favorites?

**Comment by dangwu** [comment]
Everything should be fixed now with the 4.16.3 update today. Let me know if any issues persist!

**Comment by sbc** [comment]
Amazing, thank you. Did you manage to come to an ongoing resolution with HN @dangwu?

**Comment by dangwu** [comment]
Yes, they've been totally cool about it after initial thinking I was purposefully spamming their favorites API. It turns out it was just a code mistake on my end, which was fixed in this build

**Comment by sbc** [comment]
Very excited to hear that!
